/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteCommodityArgs } from "./DeleteCommodityArgs";
import { CommodityFindManyArgs } from "./CommodityFindManyArgs";
import { CommodityFindUniqueArgs } from "./CommodityFindUniqueArgs";
import { Commodity } from "./Commodity";
import { CommodityService } from "../commodity.service";

@graphql.Resolver(() => Commodity)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CommodityResolverBase {
  constructor(
    protected readonly service: CommodityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Commodity",
    action: "read",
    possession: "any",
  })
  async _commoditiesMeta(
    @graphql.Args() args: CommodityFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Commodity])
  @nestAccessControl.UseRoles({
    resource: "Commodity",
    action: "read",
    possession: "any",
  })
  async commodities(
    @graphql.Args() args: CommodityFindManyArgs
  ): Promise<Commodity[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Commodity, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Commodity",
    action: "read",
    possession: "own",
  })
  async commodity(
    @graphql.Args() args: CommodityFindUniqueArgs
  ): Promise<Commodity | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Commodity)
  @nestAccessControl.UseRoles({
    resource: "Commodity",
    action: "delete",
    possession: "any",
  })
  async deleteCommodity(
    @graphql.Args() args: DeleteCommodityArgs
  ): Promise<Commodity | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
